name: Test Multiple Python Versions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          make install
      - name: Lint with pylint
        run: |
          make lint    
      - name: Test with pytest
        run: make test
      - name: Foramt code with Python Black
        run: make format